In [1]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
# numpy index starts from 0
# numpy slice indexing: array[start:end] where 'start' included, 'end' excluded
# 'start' can be dropped when it is 0 as shown below
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [3]:
c = a[0:2,1:3]
print(c)

[[2 3]
 [6 7]]


In [4]:
# integer indexing reduces the rank of array by 1
# below 'd' become a vector whose elements are the second row of 'a'
d = a[1,:]
print(d)
print(d.shape)

[5 6 7 8]
(4,)


In [5]:
# below 'e' is a vector whose elements are the second column of 'a'
e = a[:,1]
print(e)
print(e.shape)

[ 2  6 10]
(3,)


In [6]:
f = a[0:1,:]
g = f[0]        # [0] reduces the rank of array by 1
print('f',f)
print('g',g)
print(f.shape,g.shape)

f [[1 2 3 4]]
g [1 2 3 4]
(1, 4) (4,)


In [7]:
a = np.array([1,2])
print(a.dtype)

int32


In [8]:
b = np.array([1.0, 2.0])
print(b.dtype)

float64


In [9]:
# function 'dot' is used for inner product between vectors
a = np.random.rand(4)
b = np.random.rand(4)
c = a.dot(b)
d = np.dot(a,b)
print(a,a.shape)
print(b)
print(c,d)

[0.93646728 0.25155449 0.0110596  0.63450441] (4,)
[0.2668979  0.33865818 0.65177771 0.10170302]
0.40687155187015867 0.40687155187015867


In [10]:
# function 'dot' is also used for matrix-vector multiplication
A = np.random.rand(3,3)
x = np.random.rand(3)
y = A.dot(x)
print(A)
print(x)
print(y)

[[0.70504757 0.83504319 0.6821511 ]
 [0.73969498 0.68705258 0.2145058 ]
 [0.58834455 0.20599747 0.48171439]]
[0.20213128 0.64391974 0.62072961]
[1.10364434 0.72507231 0.55058306]


In [11]:
# function 'dot' is also used for matrix-matrix multiplication
A = np.random.rand(2,2)
B = np.random.rand(2,2)
C = A.dot(B)
print(A)
print(B)
print(C)

[[0.6868652  0.25258099]
 [0.1241488  0.52940433]]
[[0.17607805 0.45167048]
 [0.79135254 0.69732205]]
[[0.3208225  0.48636703]
 [0.44080534 0.42523966]]


In [12]:
# load a text file into an array
a = np.loadtxt('data1.txt')
print(a)

[[1.  1.2]
 [2.  2.1]
 [3.  3.2]]


In [13]:
# save an array to a binary file in NumPy .npy format
np.save('data2.npy',a)

In [14]:
# save an array to a text file
np.savetxt('data2.txt',a,fmt='%.1f')

In [15]:
# read .npy file
b = np.load('data2.npy')
print(b)

[[1.  1.2]
 [2.  2.1]
 [3.  3.2]]


In [16]:
# dictionary
d = {'a': 1, 'b': 'dadf'}
print(d,d['a'],d['b'])
c = np.arange(5)
# save multiple arrays into a binary file in NumPy .npz format
np.savez('data3.npz', a, c)
npzfile = np.load('data3.npz')
npzfile.files
print(npzfile['arr_0'])
print(npzfile['arr_1'])

{'a': 1, 'b': 'dadf'} 1 dadf
[[1.  1.2]
 [2.  2.1]
 [3.  3.2]]
[0 1 2 3 4]


In [17]:
np.savez('data4.npz', a=a, c=c)
npzfile = np.load('data4.npz')
npzfile.files
print('a',npzfile['a'])
print('c',npzfile['c'])

a [[1.  1.2]
 [2.  2.1]
 [3.  3.2]]
c [0 1 2 3 4]


In [18]:
# read binary file
a = np.fromfile(file='matlab/data.dat',dtype='float32',count=20)
print(a.shape)
print(a)

(20,)
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
x = np.random.randint(0,256,(100,100),'uint8')
print(x.shape,x.dtype)
import cv2
cv2.imwrite('test.png',x)

(100, 100) uint8


True

In [21]:
# read image as grayscale
img = cv2.imread('test.png', 0)
cv2.imshow('test', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Multi-dimensional arrays are stored in row-major ordering by default in NumPy

In [7]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print('a',a.shape,a)
# column-major ordering
b = a.reshape(2,3,order='F')
print('b',b.shape)
print(b)
c = a.reshape(2,3)
print('c',c.shape)
print(c)

a (6,) [1 2 3 4 5 6]
b (2, 3)
[[1 3 5]
 [2 4 6]]
c (2, 3)
[[1 2 3]
 [4 5 6]]
